Repository planetarium/mimir, pull requests merged in 2024-03, with the labels that each got.

#11 PDX-382: Make ArenaRanking.Avatar optional on query
  NineChroniclesUtilBackend/Models/Arena/ArenaRanking.cs
  NineChroniclesUtilBackend/Repositories/ArenaRankingRespository.cs
  NineChroniclesUtilBackend/Repositories/CpRepository.cs
Labels: Medium

#13 [PDX-390] Add IStateJsonConverter for raw hex value
  NineChroniclesUtilBackend.Store/Models/State/ArenaData.cs
  NineChroniclesUtilBackend.Store/Models/State/BaseData.cs
  NineChroniclesUtilBackend.Store/Util/BigIntegerToStringConverter.cs
  NineChroniclesUtilBackend.Store/Util/StateJsonConverter.cs
Labels: Extra Small

#14 PDX-387: Fix /arena API to fit on arena-win-rate-calculator
  NineChroniclesUtilBackend/Controllers/ArenaController.cs
  NineChroniclesUtilBackend/Repositories/ArenaRankingRespository.cs
Labels: Extra Small

#15 Add health check endpoint
  NineChroniclesUtilBackend/Program.cs
Labels: Extra Small

#16 Store dockerizing
  .github/workflows/docker.yaml
Labels: Extra Small

#12 PDX-395: Refactor initialization process
  NineChroniclesUtilBackend.Store/Client/EmptyChronicleClient.cs
  NineChroniclesUtilBackend.Store/Initializer.cs
  NineChroniclesUtilBackend.Store/Program.cs
  NineChroniclesUtilBackend.Store/Scrapper/ArenaScrapper.cs
  NineChroniclesUtilBackend.Store/Scrapper/StateGetter.cs
  NineChroniclesUtilBackend.Store/Services/EmptyChronicleStateService.cs
  NineChroniclesUtilBackend.Store/Services/IStateService.cs
  NineChroniclesUtilBackend.Store/Services/IStateStorage.cs
  NineChroniclesUtilBackend.Store/Services/MongoDbStore.cs
  NineChroniclesUtilBackend.Store/Services/StateServiceExtensions.cs
  NineChroniclesUtilBackend.Store/Services/StateStorage.cs
  NineChroniclesUtilBackend.Store/Util/BigIntegerToStringConverter.cs
  NineChroniclesUtilBackend.Store/Worker.cs
Labels: Extra Large

#18 Add emptychronicle option
  NineChroniclesUtilBackend.Store/Scrapper/ArenaScrapper.cs
  NineChroniclesUtilBackend/Controllers/DataProviderRelayController.cs
  NineChroniclesUtilBackend/Options/EmptyChronicleOption.cs
  NineChroniclesUtilBackend/Program.cs
  NineChroniclesUtilBackend/Repositories/ArenaRankingRespository.cs
  NineChroniclesUtilBackend/Repositories/CpRepository.cs
Labels: Small

#19 Add option in program
  NineChroniclesUtilBackend/Program.cs
Labels: Extra Small

#20 Fix emptychronicle response decode
  NineChroniclesUtilBackend/Repositories/CpRepository.cs
Labels: Extra Small

#24 Bump lib9c
  NineChroniclesUtilBackend.Store/Client/EmptyChronicleClient.cs
  NineChroniclesUtilBackend.Store/NineChroniclesUtilBackend.Store.csproj
  NineChroniclesUtilBackend/Arena/ArenaBulkSimulator.cs
  NineChroniclesUtilBackend/Controllers/ArenaController.cs
  NineChroniclesUtilBackend/NineChroniclesUtilBackend.csproj
Labels: Extra Small
