Repository planetarium/mimir, pull requests merged in 2024-10, with the labels that each got.

#358 Use .NET builtin JsonNode instead of 3rd-party
  Mimir.MongoDB/Bson/Serialization/Serializers/Lib9c/Items/MaterialSerializer.cs
  Mimir.MongoDB/Bson/Serialization/Serializers/Lib9c/Items/TradableMaterialSerializer.cs
  Mimir.MongoDB/Json/Converters/BigIntegerJsonConverter.cs
  Mimir.MongoDB/Json/Converters/IgnoreBencodedPropertiesConverter.cs
  Mimir.MongoDB/Json/Converters/MaterialAndIntDictionaryJsonConverter.cs
  Mimir.MongoDB/Json/Extensions/MimirBsonDocumentExtensions.cs
Labels: Squash needed

#368 Serialize as JSON with document type
  Mimir.MongoDB/Json/Extensions/MimirBsonDocumentExtensions.cs
Labels: bug

#374 fix address in `ApprovePledgeHandler`
  Mimir.Worker/ActionHandler/ApprovePledgeHandler.cs
Labels: bug, mimir.worker

#382 Rollback to Newtonsoft.Json
  Mimir.MongoDB.Tests/Bson/AllRuneDocumentTest.JsonSnapshot.verified.txt
  Mimir.MongoDB.Tests/Bson/ArenaDocumentTest.JsonSnapshot.verified.txt
  Mimir.MongoDB.Tests/Bson/AvatarDocumentTest.JsonSnapshot.verified.txt
  Mimir.MongoDB.Tests/Bson/CollectionDocumentTest.JsonSnapshot.verified.txt
  Mimir.MongoDB.Tests/Bson/CombinationSlotStateDocumentTest.JsonSnapshot.verified.txt
  Mimir.MongoDB.Tests/Bson/CombinationSlotStateDocumentTest.JsonSnapshot_WithResult.verified.txt
  Mimir.MongoDB.Tests/Bson/InventoryDocumentTest.JsonSnapshot.verified.txt
  Mimir.MongoDB.Tests/Bson/ItemSlotDocumentTest.JsonSnapshot.verified.txt
  Mimir.MongoDB.Tests/Bson/PetStateDocumentTest.JsonSnapshot.verified.txt
  Mimir.MongoDB.Tests/Bson/ProductDocumentTest.JsonSnapshot_WithFavProduct.verified.txt
  Mimir.MongoDB.Tests/Bson/ProductDocumentTest.JsonSnapshot_WithItemProduct.verified.txt
  Mimir.MongoDB.Tests/Bson/RuneSlotDocumentTest.JsonSnapshot.verified.txt
  Mimir.MongoDB.Tests/Bson/WorldInformationDocumentTest.JsonSnapshot.verified.txt
  Mimir.MongoDB/Bson/Serialization/Serializers/Lib9c/Items/MaterialSerializer.cs
  Mimir.MongoDB/Bson/Serialization/Serializers/Lib9c/Items/TradableMaterialSerializer.cs
  Mimir.MongoDB/Json/Converters/BigIntegerJsonConverter.cs
  Mimir.MongoDB/Json/Converters/IgnoreBencodedContractResolver.cs
  Mimir.MongoDB/Json/Converters/MaterialAndIntDictionaryJsonConverter.cs
  Mimir.MongoDB/Json/Extensions/MimirBsonDocumentExtensions.cs
  Mimir.MongoDB/Mimir.MongoDB.csproj
Labels: bug

#398 Remove `AllCombinationSlotStateDocument` from `TxPoller._collectionNames`
  Mimir.Worker/Poller/TxPoller.cs
Labels: bug

#410 Force lowercase database name
  Mimir.Worker/Services/MongoDbService.cs
Labels: bug

#415 bugfix: set `async` and `await` keywords to `CollectionRepository.GetByAddressAsync(address)` method
  Mimir.MongoDB/Repositories/CollectionRepository.cs
Labels: bug

#426 Publish docker image when trigerred by workflow_dispatch
  .github/workflows/docker.yaml
Labels: bug

#460 Cache transactions request
  Lib9c.GraphQL/Lib9c.GraphQL.csproj
  Lib9c.Models.Tests/Lib9c.Models.Tests.csproj
  Lib9c.Models/Lib9c.Models.csproj
  Mimir.MongoDB/Mimir.MongoDB.csproj
  Mimir.Worker/Client/HeadlessGQLClient.cs
  Mimir.Worker/Mimir.Worker.csproj
  Mimir/Mimir.csproj
Labels: bug

#462 fix: exception in `PetStateHandler`
  Mimir.E2ETests/GraphQLClientFixture.cs
  Mimir.E2ETests/HeadlessGQL/.graphqlrc.json
  Mimir.Worker/ActionHandler/PetStateHandler.cs
  Mimir.Worker/appsettings.json
Labels: bug

#464 fix: `InvalidCastException` in `PetStateHandler`
  Mimir.Worker/ActionHandler/PetStateHandler.cs
  Mimir.Worker/Util/StateGetter.cs
Labels: bug, mimir.worker

#467 fix: correct the logic to fetch transactions
  Mimir.Worker/Client/HeadlessGQLClient.cs
  Mimir.Worker/Client/Models.cs
Labels: bug, mimir.worker
