Repository planetarium/mimir, pull requests merged in 2024-04, with the labels that each got.

#25 [PDX-446] Remove 0c and use headless
  .vscode/launch.json
  NineChroniclesUtilBackend.Store/.graphqlrc.json
  NineChroniclesUtilBackend.Store/Client/EmptyChronicleClient.cs
  NineChroniclesUtilBackend.Store/Configuration.cs
  NineChroniclesUtilBackend.Store/Initializer.cs
  NineChroniclesUtilBackend.Store/NineChroniclesUtilBackend.Store.csproj
  NineChroniclesUtilBackend.Store/Program.cs
  NineChroniclesUtilBackend.Store/Queries.graphql
  NineChroniclesUtilBackend.Store/Scrapper/ArenaScrapper.cs
  NineChroniclesUtilBackend.Store/Scrapper/StateGetter.cs
  NineChroniclesUtilBackend.Store/Services/EmptyChronicleStateService.cs
  NineChroniclesUtilBackend.Store/Services/HeadlessStateService.cs
  NineChroniclesUtilBackend.Store/Services/IStateService.cs
  NineChroniclesUtilBackend.Store/Services/StateServiceExtensions.cs
  NineChroniclesUtilBackend.Store/appsettings.Development.json
  NineChroniclesUtilBackend.Store/appsettings.json
  NineChroniclesUtilBackend.Store/schema.extensions.graphql
  NineChroniclesUtilBackend.Store/schema.graphql
Labels: Extra Large

#26 Rollback mongodb store, remove state storage
  NineChroniclesUtilBackend.Store/Scrapper/ArenaScrapper.cs
  NineChroniclesUtilBackend.Store/Scrapper/StateGetter.cs
  NineChroniclesUtilBackend.Store/Services/IStateStorage.cs
  NineChroniclesUtilBackend.Store/Services/MongoDbStore.cs
  NineChroniclesUtilBackend.Store/Services/StateStorage.cs
Labels: Large

#27 PDX-396: Update arena, avatar when `battle_arena*` occurred.
  NineChroniclesUtilBackend.Store/BlockPoller.cs
  NineChroniclesUtilBackend.Store/Initializer.cs
  NineChroniclesUtilBackend.Store/Queries.graphql
  NineChroniclesUtilBackend.Store/Scrapper/ArenaScrapper.cs
  NineChroniclesUtilBackend.Store/Services/MongoDbStore.cs
Labels: Small

#28 Fallback for migrated states
  NineChroniclesUtilBackend/Controllers/AgentController.cs
Labels: bug, Extra Small
