Repository planetarium/mimir, pull requests merged in 2024-02, with the labels that each got.

#1 [Refactor] Add ArenaController, ArenaBulkSimulator
  NineChroniclesUtilBackend/Arena/ArenaBulkSimulator.cs
  NineChroniclesUtilBackend/Arena/AvatarStatesForArena.cs
  NineChroniclesUtilBackend/Controllers/ArenaController.cs
  NineChroniclesUtilBackend/Models/Arena/ArenaResult.cs
  NineChroniclesUtilBackend/Models/Arena/ArenaSimulateResponse.cs
  NineChroniclesUtilBackend/Program.cs
Labels: Large

#2 PDX-321: Use graphql code generator
  .config/dotnet-tools.json
  .gitignore
  Dockerfile
  NineChroniclesUtilBackend/.graphqlrc.json
  NineChroniclesUtilBackend/NineChroniclesUtilBackend.csproj
  NineChroniclesUtilBackend/Options/HeadlessStateServiceOption.cs
  NineChroniclesUtilBackend/Program.cs
  NineChroniclesUtilBackend/Queries.graphql
  NineChroniclesUtilBackend/Services/HeadlessStateService.cs
  NineChroniclesUtilBackend/Services/HeadlessStateServiceOptions.cs
  NineChroniclesUtilBackend/schema.extensions.graphql
  NineChroniclesUtilBackend/schema.graphql
  README.md
Labels: Extra Large

#3 [Feature] AgentController
  .vscode/launch.json
  .vscode/tasks.json
  NineChroniclesUtilBackend/Controllers/AgentController.cs
  NineChroniclesUtilBackend/Models/Agent/Avatar.cs
  NineChroniclesUtilBackend/Models/Agent/AvatarsResponse.cs
Labels: Small

#5 Adjust simulation count 10 -> 700
  NineChroniclesUtilBackend/Arena/ArenaBulkSimulator.cs
Labels: Extra Small

#6 [PDX-359] Implement jwt authorization
  NineChroniclesUtilBackend/NineChroniclesUtilBackend.csproj
  NineChroniclesUtilBackend/Options/HeadlessStateServiceOption.cs
  NineChroniclesUtilBackend/Program.cs
Labels: Extra Small

#7 Bump libplanet4
  NineChroniclesUtilBackend/.graphqlrc.json
  NineChroniclesUtilBackend/NineChroniclesUtilBackend.csproj
  NineChroniclesUtilBackend/Queries.graphql
  NineChroniclesUtilBackend/Services/HeadlessStateService.cs
  NineChroniclesUtilBackend/schema.graphql
Labels: Extra Large

#9 Merge Nine chronicles util backend.store
  .vscode/launch.json
  .vscode/tasks.json
  NineChroniclesUtilBackend.Store/Client/EmptyChronicleClient.cs
  NineChroniclesUtilBackend.Store/Configuration.cs
  NineChroniclesUtilBackend.Store/Events/ArenaDataCollectedEventArgs.cs
  NineChroniclesUtilBackend.Store/Models/BlockResponse.cs
  NineChroniclesUtilBackend.Store/Models/ScrapperResult.cs
  NineChroniclesUtilBackend.Store/Models/State/ArenaData.cs
  NineChroniclesUtilBackend.Store/Models/State/AvataData.cs
  NineChroniclesUtilBackend.Store/Models/State/BaseData.cs
  NineChroniclesUtilBackend.Store/Models/StateResponse.cs
  NineChroniclesUtilBackend.Store/Models/StoreResult.cs
  NineChroniclesUtilBackend.Store/NineChroniclesUtilBackend.Store.csproj
  NineChroniclesUtilBackend.Store/Program.cs
  NineChroniclesUtilBackend.Store/Properties/launchSettings.json
  NineChroniclesUtilBackend.Store/Scrapper/ArenaScrapper.cs
  NineChroniclesUtilBackend.Store/Scrapper/StateGetter.cs
  NineChroniclesUtilBackend.Store/Services/EmptyChronicleStateService.cs
  NineChroniclesUtilBackend.Store/Services/IStateService.cs
  NineChroniclesUtilBackend.Store/Services/MongoDbStore.cs
  NineChroniclesUtilBackend.Store/Util/JsonConverter.cs
  NineChroniclesUtilBackend.Store/Worker.cs
  NineChroniclesUtilBackend.Store/appsettings.Development.json
  NineChroniclesUtilBackend.Store/appsettings.json
  NineChroniclesUtilBackend.sln
Labels: Extra Large

#8 PDX-356: Move POST DP API to GET /arena/rankings API
  .gitignore
  NineChroniclesUtilBackend/Controllers/ArenaController.cs
  NineChroniclesUtilBackend/Models/Agent/Avatar.cs
  NineChroniclesUtilBackend/Models/Arena/ArenaRanking.cs
  NineChroniclesUtilBackend/NineChroniclesUtilBackend.csproj
  NineChroniclesUtilBackend/Options/DatabaseOption.cs
  NineChroniclesUtilBackend/Program.cs
  NineChroniclesUtilBackend/Repositories/ArenaRankingRespository.cs
  NineChroniclesUtilBackend/Repositories/CpRepository.cs
  NineChroniclesUtilBackend/Services/MongoDBCollectionService.cs
Labels: Large
